apiVersion: v1
kind: Service
metadata:
  name: aigov-core
  namespace: aigov-core
  labels:
    app.kubernetes.io/name: aigov-core
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: aigov-core
  ports:
    - name: http
      port: 8088
      targetPort: http
      protocol: TCP
